# Hurricane Modeling

*Week 5*

In [48]:
# Standard imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import urllib.request
import linecache

# Retrieve the HURDAT2 dataset from NOAA
url = 'https://www.nhc.noaa.gov/data/hurdat/hurdat2-1851-2018-120319.txt'
rawfile = 'hurdat2.txt'
urllib.request.urlretrieve(url, rawfile)

# Clean up the file:
# Make each row have its hurricane ID and name

current = 0

cleanfile = 'hurdat2_clean.txt'
with open(rawfile, 'r') as source, open(cleanfile, 'w') as dest:
    for i, line in enumerate(source):
        if current == i:
            heads = [a.lstrip().rstrip() for a in line.split(', ')]
            rows = int(heads[2][:-1])
            for row in range(1,rows+1):
                r = linecache.getline(rawfile, current+row+1)
                time = r[0:4] + '-' + r[4:6] + '-' + r[6:8] + ' ' + r[10:12] + ':' + r[12:14]
                n = heads[0] + ', ' + heads[1] + ', ' + time + ', ' + r[14:]
                dest.write(n)
            current += rows+1

In [58]:
n = [a for a in 'abcdefghijklmnopqrstuv']
data = pd.read_csv(cleanfile, header=None, names=n, index_col=None, skipinitialspace=True)
data['b'] =  pd.to_datetime(data['b'], format='%Y-%m-%d %H:%M')
data.head(30)

,a,b,c,d,e,f,g,h,i,j,...,m,n,o,p,q,r,s,t,u,v
AL011851,UNNAMED,1851-06-25 00:00:00,NaN,NaN,HU,28.0N,94.8W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-25 06:00:00,NaN,NaN,HU,28.0N,95.4W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-25 12:00:00,NaN,NaN,HU,28.0N,96.0W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-25 18:00:00,NaN,NaN,HU,28.1N,96.5W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-25 21:00:00,NaN,L,HU,28.2N,96.8W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-26 00:00:00,NaN,NaN,HU,28.2N,97.0W,70,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-26 06:00:00,NaN,NaN,TS,28.3N,97.6W,60,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-26 12:00:00,NaN,NaN,TS,28.4N,98.3W,60,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-26 18:00:00,NaN,NaN,TS,28.6N,98.9W,50,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-27 00:00:00,NaN,NaN,TS,29.0N,99.4W,50,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-27 06:00:00,NaN,NaN,TS,29.5N,99.8W,40,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-27 12:00:00,NaN,NaN,TS,30.0N,100.0W,40,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-27 18:00:00,NaN,NaN,TS,30.5N,100.1W,40,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL011851,UNNAMED,1851-06-28 00:00:00,NaN,NaN,TS,31.0N,100.2W,40,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL021851,UNNAMED,1851-07-05 12:00:00,NaN,NaN,HU,22.2N,97.6W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL031851,UNNAMED,1851-07-10 12:00:00,NaN,NaN,TS,12.0N,60.0W,50,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-16 00:00:00,NaN,NaN,TS,13.4N,48.0W,40,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-16 06:00:00,NaN,NaN,TS,13.7N,49.5W,40,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-16 12:00:00,NaN,NaN,TS,14.0N,51.0W,50,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-16 18:00:00,NaN,NaN,TS,14.4N,52.8W,50,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-17 00:00:00,NaN,NaN,TS,14.9N,54.6W,60,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-17 06:00:00,NaN,NaN,TS,15.4N,56.5W,60,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-17 12:00:00,NaN,NaN,HU,15.9N,58.5W,70,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-17 18:00:00,NaN,NaN,HU,16.1N,60.4W,70,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-18 00:00:00,NaN,NaN,HU,16.6N,62.5W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-18 06:00:00,NaN,NaN,HU,16.9N,64.1W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-18 12:00:00,NaN,NaN,HU,17.2N,66.0W,90,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-18 18:00:00,NaN,NaN,HU,17.6N,67.6W,90,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-19 00:00:00,NaN,NaN,HU,18.0N,69.3W,90,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
AL041851,UNNAMED,1851-08-19 06:00:00,NaN,NaN,HU,18.4N,71.1W,70,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN